apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels:
    app: nginx-web
spec:
  selector:
    matchLabels:
      app: nginx-web
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
