apiVersion: analysis.scaleops.sh/v1alpha1
kind: Policy
metadata:
  name: production-no-inplace
  namespace: week1
spec:
  type: Optimize
  policyOptimize:
    rightSizePolicy:
      windowByResource:
        cpu: 24h
        memory: 24h
      requestsConfigs:
        cpu:
          headroomPercentage: 10
          percentilePercentage: 93
          minAllowed: 10m
          maxAllowed: 0m
        memory:
          headroomPercentage: 5
          percentilePercentage: 93
          minAllowed: 0.02Gi
          maxAllowed: 0Gi
      limitConfigs:
        cpu:
          keepLimit: true
        memory:
          keepLimit: true
      nodeCappingPolicy:
        nodeCappingAuto: true
    fastReaction:
      enabled:
        cpu: true
        memory: true
  updatePolicy:
    updateByTypeMode:
      deployment: Ongoing
      statefulSet: OnCreate
      daemonSet: OnCreate
      job: OnCreate
      family: OnCreate
      deploymentConfig: OnCreate
      argoRollout: Ongoing
    minReplicas: 1
    requiredWindowCoveragePercentage: 0
    allowRollingUpdate: true
    binPackUnEvictablePods: true
    inPlaceUpdateStrategy:
      enableInPlaceForOngoingStrategy: false
      enableInPlaceForUponPodCreationStrategy: false
